import json
import random
from datetime import date, timedelta
from pathlib import Path

import numpy as np
from faker import Faker
from pydantic import ValidationError

from app.schema import LableMeta

SEED = 32

PERSONAS = {
    "FOCUS": {
        "total_meetings": (2, 1, 0, 4, True),
        "meeting_hours_per_day": (2.0, 1.0, 0.0, 4.0, False),
        "average_gap_between_meetings_minutes": (55.0, 17.5, 20.0, 90.0, False),
        "messages_sent_after_8pm": (1, 1, 0, 2, True),
        "context_switches_per_hour": (3, 1, 0, 5, True),
    },
    "NEUTRAL": {
        "total_meetings": (6, 1, 4, 8, True),
        "meeting_hours_per_day": (5.75, 1.125, 3.5, 8.0, False),
        "average_gap_between_meetings_minutes": (29.0, 9.25, 10.5, 47.5, False),
        "messages_sent_after_8pm": (9, 2, 4, 14, True),
        "context_switches_per_hour": (6, 2, 3, 10, True),
    },
    "BURNOUT": {
        "total_meetings": (10, 1, 7, 12, True),
        "meeting_hours_per_day": (9.5, 1.25, 7.0, 12.0, False),
        "average_gap_between_meetings_minutes": (3.0, 1.0, 1.0, 5.0, False),
        "messages_sent_after_8pm": (17, 4, 8, 25, True),
        "context_switches_per_hour": (11, 2, 7, 15, True),
    }
}

# as std increase the bell curve becomes wider
def sample_feature(mean, std, lo, hi, round_int):
    raw = np.random.normal(mean, std) # creates number using a Gaussian Distribution
    clipped = np.clip(raw, lo, hi) # to bound the values generated by the distribution
    return int(round(clipped)) if round_int else round(float(clipped), 1)

def generate_row(label: str, log_date : date, user_id : str) -> LableMeta:
    params = PERSONAS[label]
    return LableMeta(
        user_id=user_id,
        date=log_date,
        total_meetings=sample_feature(*params["total_meetings"]),
        meeting_hours_per_day=sample_feature(*params["meeting_hours_per_day"]),
        average_gap_between_meetings_minutes=sample_feature(*params["average_gap_between_meetings_minutes"]),
        messages_sent_after_8pm=sample_feature(*params["messages_sent_after_8pm"]),
        context_switches_per_hour=sample_feature(*params["context_switches_per_hour"]),
        label=label
    )

def generate_dataset(n_users: int, week_start: date) -> list[dict]:
    random.seed(SEED)
    np.random.seed(SEED)
    Faker.seed(SEED)
    fake = Faker()

    week_days = [week_start + timedelta(days=i) for i in range(5)]
    labels = ["FOCUS", "NEUTRAL", "BURNOUT"]
    weights = [0.3, 0.4, 0.3]

    rows: list[dict] = []
    skipped = 0

    for _ in range(n_users):
        user_id = fake.uuid4()
        label = random.choices(labels, weights=weights, k=1)[0]

        for log_date in week_days:
            while True:
                try:
                    row = generate_row(label, log_date, user_id)
                    rows.append(row.model_dump(mode="json"))
                    break
                except ValidationError:
                    skipped += 1

    print(
        f"generated {len(rows)} rows for {n_users} users x {len(week_days)} days, "
        f"skipped {skipped} inconsistent samples"
    )
    return rows


if __name__ == "__main__":
    dataset = generate_dataset(n_users=100, week_start=date(2026, 6, 29))
    out_path = Path(__file__).resolve().parent.parent / "data" / "synthetic_logs.json"
    out_path.parent.mkdir(exist_ok=True)
    out_path.write_text(json.dumps(dataset, indent=2))
    print(f"wrote {out_path}")